"""empty message

Revision ID: 174656f6b8e4
Revises: 32ae7f004887
Create Date: 2019-12-09 17:15:03.148784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '174656f6b8e4'
down_revision = '32ae7f004887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
